# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db-mongo:27017
      - MONGODB_DB=NESJS-BASIC
      - MONGODB_USER=root
      - MONGODB_PASS=123456
      # - DB_HOST=host.docker.internal
    expose:
      - 8080
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.23.3
    ports:
      - 3000:80
    volumes:
      - ./dist:/usr/share/nginx/html
volumes:
  mongodb:

    # docker compose -p nest up -d
